/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    borderRadius: {
      none: '0px',
      sm: '8px',
      DEFAULT: '8px',
      md: '12px',
      lg: '16px',
      xl: '24px',
      full: '9999px',
    },
    boxShadow: {
      none: 'none',
      sm: '0 1px 3px rgba(0,0,0,0.06)',
      DEFAULT: '0 1px 3px rgba(0,0,0,0.06)',
      md: '0 4px 12px rgba(0,0,0,0.08)',
      lg: '0 8px 24px rgba(0,0,0,0.10)',
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        display:      ['56px', { lineHeight: '1.0',  letterSpacing: '-0.01em', fontWeight: '700' }],
        'heading-1':  ['28px', { lineHeight: '1.2',  letterSpacing: '-0.01em', fontWeight: '700' }],
        'heading-2':  ['20px', { lineHeight: '1.3',  letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-medium':['16px', { lineHeight: '1.6',  fontWeight: '500' }],
        body:         ['16px', { lineHeight: '1.6',  fontWeight: '400' }],
        label:        ['13px', { lineHeight: '1.4',  letterSpacing: '0.02em', fontWeight: '500' }],
        caption:      ['12px', { lineHeight: '1.4',  letterSpacing: '0.02em', fontWeight: '400' }],
      },
      colors: {
        background:       '#f8f8f6',
        surface:          '#f0f0ed',
        'surface-raised': '#eaeae6',
        border:           '#e2e2de',
        'text-primary':   '#1a1a18',
        'text-secondary': '#6b6b66',
        'text-muted':     '#a0a09a',
        'green-bg':       '#e8f0e8',
        'green-text':     '#3a6b3a',
        'green-mark':     '#c8dfc8',
        'amber-bg':       '#f0ebe0',
        'amber-text':     '#7a5c1e',
        'amber-mark':     '#e8d5a8',
        'red-bg':         '#f0e8e8',
        'red-text':       '#8b3a3a',
        'red-mark':       '#f0c8c8',
        'nav-icon-active':   '#1a1a18',
        'nav-icon-inactive': '#a0a09a',
        'drawer-bg':       '#f0f0ed',
        'btn-primary-bg':  '#1a1a18',
        'btn-primary-text':'#f8f8f6',
        'btn-secondary-bg':'#eaeae6',
        'btn-secondary-text':'#1a1a18',
        'btn-disabled':    '#d4d4d0',
        error:             '#ba1a1a',
      },
      spacing: {
        'space-1':  '4px',
        'space-2':  '8px',
        'space-3':  '12px',
        'space-4':  '16px',
        'space-5':  '20px',
        'space-6':  '24px',
        'space-8':  '32px',
        'space-10': '40px',
        'mobile-padding':  '24px',
        'tablet-padding':  '48px',
        'desktop-padding': '80px',
      },
    },
  },
  plugins: [],
}
